### ISSUE TITLE
tarefa

### ISSUE THREAD

**Issue by isasmin** [atoiolindo/Vitrine-Sem-Fim#1]
comentar TODO o codigo, inclusive as coisas minimas

css do menu, pagecadastro, login, index e o home

php home, login, menu, page cadastro lista e pesquisar

**Comment by Kingnike1** [comment]
**"Comentei o código todo, Yasmin! Tudo bonitinho e explicadinho, mas se eu tiver feito alguma besteira ou se alguém encontrar algo que pareça um erro de novato, é só me chamar! Pode ser sinal de fumaça, whatsapp, ou até mesmo uma ligação urgente! Se não, me avise se encontrar algo que faça mais sentido que eu e posso corrigir rapidinho. Tô por aqui, pronto pra qualquer emergência de código. Vamo que vamo!"**

**Comment by isasmin** [comment]
> **"Comentei o código todo, Yasmin! Tudo bonitinho e explicadinho, mas se eu tiver feito alguma besteira ou se alguém encontrar algo que pareça um erro de novato, é só me chamar! Pode ser sinal de fumaça, whatsapp, ou até mesmo uma ligação urgente! Se não, me avise se encontrar algo que faça mais sentido que eu e posso corrigir rapidinho. Tô por aqui, pronto pra qualquer emergência de código. Vamo que vamo!"**

Valeu Pablo, você é 10!!!

Vou dar uma conferida aqui agora, muito obrigada.
